ARG VLLM_VERSION=0.9.1
FROM vllm/vllm-openai:${VLLM_VERSION}

ENV YQ_VERSION=v4.45.4
ENV YQ_BINARY=yq_linux_amd64

RUN curl -L https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/${YQ_BINARY} -o /usr/bin/yq && \
    chmod +x /usr/bin/yq

COPY docker-entrypoint-vllm.sh /usr/bin/docker-entrypoint-vllm.sh
RUN chmod +x /usr/bin/docker-entrypoint-vllm.sh

WORKDIR /workspace

ENTRYPOINT ["/usr/bin/docker-entrypoint-vllm.sh"]
