wandb:
  run_name: "deepseek/deepseek-chat-v3 (0324)" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: openai-compatible
batch_size: 32 # vllmは256, apiは32を推奨
#inference_interval: 1 # seconds
base_url: "https://api.deepseek.com/v1"

model:
  pretrained_model_name_or_path: "deepseek-chat" #if you use openai api, put the name of model
  bfcl_model_name: "DeepSeek-V3-FC"
  size_category: "api"
  size: null
  release_date: "3/24/2025"

testmode: false