wandb:
  run_name: "openai/gpt-oss-20b" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm-external  
base_url: https://openrouter.ai/api/v1
batch_size: 32 # vllmは256, apiは32を推奨
# inference_interval: 1 # seconds

model:
  pretrained_model_name_or_path: "openai/gpt-oss-20b" #if you use openai api, put the name of model
  size_category: "10B≤ <30B"
  size: 20000000000
  release_date: "8/5/2025"

generator:
  temperature: 1.0
  max_tokens: 8192  # 回答用のトークン数
  extra_body:
    reasoning:
      max_tokens: 100000  # reasoning用のトークン数
      exclude: true  # reasoningトークンを出力に含めない
    provider:
      order: ["deepinfra/fp4"]