wandb:
  run_name: "qwen/qwen3.5-flash-02-23: openrouter-lowcost"

api: openai-compatible
base_url: https://openrouter.ai/api/v1
batch_size: 4
inference_interval: 1

model:
  pretrained_model_name_or_path: qwen/qwen3.5-flash-02-23
  bfcl_model_id: OpenRouter-FC
  base_model: unknown
  size_category: api
  size: null
  release_date: 2/23/2026

generator:
  temperature: 0.0
  top_p: 1.0
  parallel_tool_calls: true
  max_tokens: 8192
  extra_body:
    provider:
      allow_fallbacks: false

jaster:
  override_max_tokens: 8192

jbbq:
  generator_config:
    max_tokens: 8192

toxicity:
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0

jtruthfulqa:
  generator_config:
    max_tokens: 8192

swebench:
  max_tokens: 8192
  fc_enabled: true
  fc_tool_choice: auto
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

mtbench:
  max_new_token: 8192
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false
  temperature_override:
    writing: 0.7
    roleplay: 0.7
    extraction: 0.0
    math: 0.0
    coding: 0.0
    reasoning: 0.0
    stem: 0.1
    humanities: 0.1

bfcl:
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

hallulens:
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

hallulens_zh_tw:
  generator_config:
    max_tokens: 1024
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

hle:
  max_completion_tokens: 8192
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

arc_agi:
  max_output_tokens: 8192

m_ifeval:
  generator_config:
    max_tokens: 8192
    temperature: 0.0
    top_p: 1.0

ifeval_zh_tw:
  generator_config:
    max_tokens: 2048
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

ts_bench:
  generator_config:
    max_tokens: 64
    temperature: 0.0
    top_p: 1.0
    extra_body:
      provider:
        allow_fallbacks: false

openai:
  http_timeout:
    connect: 10.0
    read: 900.0
    write: 300.0
    pool: 30.0
