wandb:
  run_name: meta-llama/Meta-Llama-3-8B-Instruct
api: vllm
base_url: "http://llm-stack-vllm-1:8000/v1"  # vLLMコンテナの正しいURL（Docker内から接続）
batch_size: 256
model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct #if you use openai api, put the name of model
  bfcl_model_name: "" # check the model name in "llm-leaderboard/scripts/evaluator/evaluate_utils/bfcl_pkg/SUPPORTED_MODELS.md"
  chat_template: meta-llama/Meta-Llama-3-8B-Instruct
  size_category: <10B
  size: 8030261248
  release_date: 4/18/2024
  max_model_len: 16384
