wandb:
  run_name: "openai/gpt-5.6-sol: max-effort"
api: openai_responses
batch_size: 8
model:
  pretrained_model_name_or_path: gpt-5.6-sol
  bfcl_model_id: "OpenAIResponsesHandler-FC"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: null

generator:
  parallel_tool_calls: true
  max_tokens: 128000
  text:
    verbosity: medium
  extra_body:
    reasoning:
      effort: max

jaster:
  override_max_tokens: 128000
jbbq:
  generator_config:
    max_tokens: 128000
toxicity:
  generator_config:
    max_tokens: 128000
jtruthfulqa:
  generator_config:
    max_tokens: 128000
swebench:
  max_tokens: 128000
  fc_enabled: true
mtbench:
  generator_config:
    max_tokens: 128000
bfcl:
  generator_config:
    max_tokens: 128000
    include:
      - reasoning.encrypted_content
  handler_config:
    openai_responses:
      inject_bfcl_fc_system_prompt: true
hallulens:
  generator_config:
    max_tokens: 128000
hle:
  generator_config:
    max_tokens: 128000
arc_agi:
  max_output_tokens: 128000
m_ifeval:
  generator_config:
    max_tokens: 128000
openai:
  http_timeout:
    connect: 10.0
    read: 1800.0
    write: 300.0
    pool: 30.0
