wandb:
  run_name: "meta-llama/llama-4-scout" # use run_name defined above

# if you don't use api, please set "api" as "false"
# if you use api, please select from "openai", "anthoropic", "google", "cohere", "vllm"
api: vllm-external
batch_size: 32 # vllmは256, apiは32を推奨
base_url: "https://openrouter.ai/api/v1"

model:
  use_wandb_artifacts: false
  pretrained_model_name_or_path: "meta-llama/llama-4-scout" #if you use openai api, put the name of model
  size_category: "30B≤"
  size: 109000000000
  release_date: "4/5/2025"
  max_model_len: 2500