wandb:
  run_name: "anthropic/claude-sonnet-5: direct-high"
api: anthropic
batch_size: 4
model:
  pretrained_model_name_or_path: claude-sonnet-5
  bfcl_model_id: "Claude-FC"
  base_model: "unknown"
  size_category: api
  size: null
  release_date: null

generator:
  max_tokens: 128000
  effort: high

jaster:
  override_max_tokens: 128000
jbbq:
  generator_config:
    max_tokens: 128000
toxicity:
  generator_config:
    max_tokens: 128000
jtruthfulqa:
  generator_config:
    max_tokens: 128000
swebench:
  max_tokens: 128000
  fc_enabled: true
mtbench:
  generator_config:
    max_tokens: 128000
bfcl:
  generator_config:
    max_tokens: 128000
hallulens:
  generator_config:
    max_tokens: 128000
hle:
  generator_config:
    max_tokens: 128000
arc_agi:
  max_output_tokens: 128000
m_ifeval:
  generator_config:
    max_tokens: 128000
